name: Python CI/CD  

on: [push]  

jobs:  
  test:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4  
      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.11'  
      - name: Install dependencies  
        run: pip install -r requirements.txt  
      - name: Run tests  
        run: pytest  # Add tests later!  

  deploy:  
    needs: test  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4  
      - name: Deploy to Render  
        run: |  
          echo "TODO: Add Render/Heroku deployment"  